spring.application.name=em_project
#is for run our project in 9090 port
server.port=9090    
#spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management
#use for dtatabase connection username and password
spring.datasource.username=root
spring.datasource.password=root
#use for database connection driver class name
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#use for automatically create tables in database using hibernate
spring.jpa.hibernate.ddl-auto=update
#to show all sql queries in console
spring.jpa.show-sql=true